export interface AdmissionDecision {
  allowed: boolean
  reason?:
    | 'generated-build-directory'
    | 'generated-build-file'
    | 'temporary-file'
}

/**
 * Directories generated by Electron / packager builds that should never be auto-discovered.
 * Case-insensitive comparison against path segments.
 * Note: Never blanket-ignore release, releases, builds, output, out, bin.
 */
export const GENERATED_BUILD_DIRECTORIES = new Set([
  'win-unpacked',
  'win-unpacked.tmp',
  'linux-unpacked',
  'linux-arm64-unpacked',
  'app.asar.unpacked',
  'dist_electron',
])

/**
 * Bundled license files generated by Electron / Chromium that flood indexes.
 * Case-insensitive comparison against base filenames.
 * Note: Do NOT blanket-ignore LICENSE* as users may intentionally have license docs.
 */
export const GENERATED_BUILD_FILENAMES = new Set([
  'licenses.chromium.html',
  'license.electron.txt',
])

const TEMPORARY_FILE_PATTERN = /\.(tmp|temp|crdownload|partial|part|lock|lck|swp|bak)$/i

/**
 * Checks whether a path contains any generated build directories or generated build filenames.
 * Returns true if the path violates generated directory or generated filename policies.
 */
export function isGeneratedArtifactPath(path: string): boolean {
  const normalized = path.replace(/\\/g, '/')
  const segments = normalized.split('/').filter(Boolean)
  if (segments.length === 0) return false

  for (const seg of segments) {
    if (GENERATED_BUILD_DIRECTORIES.has(seg.toLowerCase())) {
      return true
    }
  }

  const fileName = segments[segments.length - 1]
  if (fileName && GENERATED_BUILD_FILENAMES.has(fileName.toLowerCase())) {
    return true
  }

  return false
}

/**
 * Evaluates whether a discovered path should be admitted into document search indexing.
 */
export function discoveredPathAdmission(path: string): AdmissionDecision {
  const normalized = path.replace(/\\/g, '/')
  const segments = normalized.split('/').filter(Boolean)
  if (segments.length === 0) {
    return { allowed: true }
  }

  for (const seg of segments) {
    if (GENERATED_BUILD_DIRECTORIES.has(seg.toLowerCase())) {
      return { allowed: false, reason: 'generated-build-directory' }
    }
  }

  const fileName = segments[segments.length - 1]
  if (fileName) {
    const lowerFileName = fileName.toLowerCase()
    if (GENERATED_BUILD_FILENAMES.has(lowerFileName)) {
      return { allowed: false, reason: 'generated-build-file' }
    }
    if (fileName.startsWith('~$') || TEMPORARY_FILE_PATTERN.test(fileName)) {
      return { allowed: false, reason: 'temporary-file' }
    }
  }

  return { allowed: true }
}
