import { createI18n, type Lang, type LangDicts, type Params } from '@genoffice/i18n'

/**
 * Strings for the Home assistant's history, messages and empty state. Kept out of
 * the shared strings.ts so upstream merges stay trivial. `zh` defines the key
 * set; every other language below is type-checked against it. Languages without a
 * dedicated translation reuse the English text.
 */
const zh = {
  homeChatHistory: '聊天记录',
  homeChatSearch: '搜索对话',
  homeChatNoHistory: '你的对话会显示在这里。',
  homeChatNoMatches: '没有与“{q}”匹配的对话。',
  homeChatGroupToday: '今天',
  homeChatGroupYesterday: '昨天',
  homeChatGroupWeek: '过去 7 天',
  homeChatGroupOlder: '更早',
  homeChatRename: '重命名',
  homeChatRenameLabel: '对话名称',
  homeChatDelete: '删除',
  homeChatDeleted: '已删除对话',
  homeChatUndo: '撤销',
  homeChatClearAll: '清除全部记录',
  homeChatClearConfirm: '再次点击以全部清除',
  homeChatCleared: '已清除记录',
  homeChatToggleHistory: '显示或隐藏聊天记录',
  homeChatCopy: '复制',
  homeChatCopied: '已复制',
  homeChatRetry: '重试',
  homeChatJumpLatest: '跳到最新',
  homeChatShowEarlier: '显示更早的 {n} 条消息',
  homeChatResize: '调整聊天窗口大小',
  homeChatSuggest1: '找出我上周打开的预算表',
  homeChatSuggest2: '哪些文档提到了第三季度发布？',
  homeChatSuggest3: '总结我昨天看的那份合同',
  homeChatSourceStale: '已更改',
  homeChatSourceMissing: '已丢失',
  homeChatSourceStaleHint: '此文件在读取后发生了变化，请打开确认。',
  homeChatSourceSkeleton: '仅保留框架',
  homeChatSourceSkeletonHint: '仅保留文档框架，打开可阅读完整内容。',
  homeChatSourceMissingHint: '此文件已不在原来保存的位置。',
  homeChatLoadFailed: '无法打开此对话。',
  homeChatInterrupted: '此回复被中断。',
  homeChatWorking: '正在回复…',
  homeChatDone: '已回复',
  homeChatErrorChip: '出错了，点击查看',
  homeChatStopChip: '停止',
  homeChatElapsed: '{n} 秒',
}

type Dict = Record<keyof typeof zh, string>

const en = {
  homeChatHistory: 'Chat history',
  homeChatSearch: 'Search chats',
  homeChatNoHistory: 'Your chats will show up here.',
  homeChatNoMatches: 'No chats match "{q}".',
  homeChatGroupToday: 'Today',
  homeChatGroupYesterday: 'Yesterday',
  homeChatGroupWeek: 'Previous 7 days',
  homeChatGroupOlder: 'Older',
  homeChatRename: 'Rename',
  homeChatRenameLabel: 'Chat name',
  homeChatDelete: 'Delete',
  homeChatDeleted: 'Chat deleted',
  homeChatUndo: 'Undo',
  homeChatClearAll: 'Clear all history',
  homeChatClearConfirm: 'Click again to clear all',
  homeChatCleared: 'History cleared',
  homeChatToggleHistory: 'Show or hide chat history',
  homeChatCopy: 'Copy',
  homeChatCopied: 'Copied',
  homeChatRetry: 'Try again',
  homeChatJumpLatest: 'Jump to latest',
  homeChatShowEarlier: 'Show {n} earlier messages',
  homeChatResize: 'Resize chat',
  homeChatSuggest1: 'Find the budget spreadsheet I opened last week',
  homeChatSuggest2: 'Which documents mention the Q3 launch?',
  homeChatSuggest3: 'Summarize the contract I was reading yesterday',
  homeChatSourceStale: 'Changed',
  homeChatSourceMissing: 'Missing',
  homeChatSourceStaleHint: 'This file changed after it was read. Open it to check.',
  homeChatSourceSkeleton: 'Outline only',
  homeChatSourceSkeletonHint: 'Only the outline is kept. Open the file to read it in full.',
  homeChatSourceMissingHint: 'This file is no longer at its saved location.',
  homeChatLoadFailed: 'Could not open this chat.',
  homeChatInterrupted: 'This reply was interrupted.',
  homeChatWorking: 'Replying…',
  homeChatDone: 'Replied',
  homeChatErrorChip: 'Something went wrong — click to view',
  homeChatStopChip: 'Stop',
  homeChatElapsed: '{n}s',
} satisfies Dict

const vi = {
  homeChatHistory: 'Lịch sử trò chuyện',
  homeChatSearch: 'Tìm cuộc trò chuyện',
  homeChatNoHistory: 'Các cuộc trò chuyện của bạn sẽ hiện ở đây.',
  homeChatNoMatches: 'Không có cuộc trò chuyện nào khớp “{q}”.',
  homeChatGroupToday: 'Hôm nay',
  homeChatGroupYesterday: 'Hôm qua',
  homeChatGroupWeek: '7 ngày trước',
  homeChatGroupOlder: 'Cũ hơn',
  homeChatRename: 'Đổi tên',
  homeChatRenameLabel: 'Tên cuộc trò chuyện',
  homeChatDelete: 'Xóa',
  homeChatDeleted: 'Đã xóa cuộc trò chuyện',
  homeChatUndo: 'Hoàn tác',
  homeChatClearAll: 'Xóa toàn bộ lịch sử',
  homeChatClearConfirm: 'Nhấn lần nữa để xóa hết',
  homeChatCleared: 'Đã xóa lịch sử',
  homeChatToggleHistory: 'Hiện hoặc ẩn lịch sử',
  homeChatCopy: 'Sao chép',
  homeChatCopied: 'Đã sao chép',
  homeChatRetry: 'Thử lại',
  homeChatJumpLatest: 'Xuống tin mới nhất',
  homeChatShowEarlier: 'Hiện {n} tin nhắn cũ hơn',
  homeChatResize: 'Đổi kích thước khung chat',
  homeChatSuggest1: 'Tìm bảng tính ngân sách tôi đã mở tuần trước',
  homeChatSuggest2: 'Tài liệu nào nhắc đến kế hoạch ra mắt quý 3?',
  homeChatSuggest3: 'Tóm tắt hợp đồng tôi đọc hôm qua',
  homeChatSourceStale: 'Đã đổi',
  homeChatSourceMissing: 'Không còn',
  homeChatSourceStaleHint: 'Tệp này đã thay đổi sau khi được đọc. Hãy mở ra để kiểm tra.',
  homeChatSourceSkeleton: 'Chỉ giữ khung',
  homeChatSourceSkeletonHint: 'Chỉ giữ phần khung — mở để đọc đầy đủ',
  homeChatSourceMissingHint: 'Tệp không còn ở vị trí đã lưu.',
  homeChatLoadFailed: 'Không mở được cuộc trò chuyện này.',
  homeChatInterrupted: 'Câu trả lời này bị gián đoạn.',
  homeChatWorking: 'Đang trả lời…',
  homeChatDone: 'Đã trả lời',
  homeChatErrorChip: 'Có lỗi — bấm để xem',
  homeChatStopChip: 'Dừng',
  homeChatElapsed: '{n} giây',
} satisfies Dict

const ja = {
  homeChatHistory: 'チャット履歴',
  homeChatSearch: 'チャットを検索',
  homeChatNoHistory: 'チャットはここに表示されます。',
  homeChatNoMatches: '「{q}」に一致するチャットはありません。',
  homeChatGroupToday: '今日',
  homeChatGroupYesterday: '昨日',
  homeChatGroupWeek: '過去 7 日間',
  homeChatGroupOlder: 'それ以前',
  homeChatRename: '名前を変更',
  homeChatRenameLabel: 'チャット名',
  homeChatDelete: '削除',
  homeChatDeleted: 'チャットを削除しました',
  homeChatUndo: '元に戻す',
  homeChatClearAll: '履歴をすべて消去',
  homeChatClearConfirm: 'もう一度クリックですべて消去',
  homeChatCleared: '履歴を消去しました',
  homeChatToggleHistory: 'チャット履歴の表示を切り替え',
  homeChatCopy: 'コピー',
  homeChatCopied: 'コピーしました',
  homeChatRetry: 'やり直す',
  homeChatJumpLatest: '最新へ移動',
  homeChatShowEarlier: '以前の {n} 件のメッセージを表示',
  homeChatResize: 'チャットのサイズを変更',
  homeChatSuggest1: '先週開いた予算表を探して',
  homeChatSuggest2: '第 3 四半期のリリースに触れている文書は？',
  homeChatSuggest3: '昨日読んだ契約書を要約して',
  homeChatSourceStale: '変更あり',
  homeChatSourceMissing: '見つかりません',
  homeChatSourceStaleHint: 'このファイルは読み取り後に変更されました。開いて確認してください。',
  homeChatSourceSkeleton: 'アウトラインのみ',
  homeChatSourceSkeletonHint: 'アウトラインのみ保持しています。開くと全文を読めます。',
  homeChatSourceMissingHint: 'このファイルは保存場所にありません。',
  homeChatLoadFailed: 'このチャットを開けませんでした。',
  homeChatInterrupted: 'この返信は中断されました。',
  homeChatWorking: '返信中…',
  homeChatDone: '返信しました',
  homeChatErrorChip: 'エラーが発生しました。クリックして確認',
  homeChatStopChip: '停止',
  homeChatElapsed: '{n} 秒',
} satisfies Dict

const ko = {
  homeChatHistory: '채팅 기록',
  homeChatSearch: '채팅 검색',
  homeChatNoHistory: '대화가 여기에 표시됩니다.',
  homeChatNoMatches: '"{q}"와(과) 일치하는 채팅이 없습니다.',
  homeChatGroupToday: '오늘',
  homeChatGroupYesterday: '어제',
  homeChatGroupWeek: '지난 7일',
  homeChatGroupOlder: '이전',
  homeChatRename: '이름 바꾸기',
  homeChatRenameLabel: '채팅 이름',
  homeChatDelete: '삭제',
  homeChatDeleted: '채팅을 삭제했습니다',
  homeChatUndo: '실행 취소',
  homeChatClearAll: '기록 모두 지우기',
  homeChatClearConfirm: '한 번 더 누르면 모두 지웁니다',
  homeChatCleared: '기록을 지웠습니다',
  homeChatToggleHistory: '채팅 기록 표시 전환',
  homeChatCopy: '복사',
  homeChatCopied: '복사됨',
  homeChatRetry: '다시 시도',
  homeChatJumpLatest: '최신으로 이동',
  homeChatShowEarlier: '이전 메시지 {n}개 보기',
  homeChatResize: '채팅 크기 조절',
  homeChatSuggest1: '지난주에 연 예산 스프레드시트 찾아줘',
  homeChatSuggest2: '3분기 출시를 언급한 문서는?',
  homeChatSuggest3: '어제 읽은 계약서를 요약해줘',
  homeChatSourceStale: '변경됨',
  homeChatSourceMissing: '없음',
  homeChatSourceStaleHint: '이 파일은 읽은 뒤 변경되었습니다. 열어서 확인하세요.',
  homeChatSourceSkeleton: '개요만 보관',
  homeChatSourceSkeletonHint: '개요만 보관 중입니다. 파일을 열면 전체를 읽을 수 있습니다.',
  homeChatSourceMissingHint: '이 파일이 저장된 위치에 없습니다.',
  homeChatLoadFailed: '이 채팅을 열 수 없습니다.',
  homeChatInterrupted: '이 답변이 중단되었습니다.',
  homeChatWorking: '답변 중…',
  homeChatDone: '답변 완료',
  homeChatErrorChip: '오류가 발생했습니다. 눌러서 확인',
  homeChatStopChip: '중지',
  homeChatElapsed: '{n}초',
} satisfies Dict

const zhTW = {
  homeChatHistory: '聊天記錄',
  homeChatSearch: '搜尋對話',
  homeChatNoHistory: '你的對話會顯示在這裡。',
  homeChatNoMatches: '沒有與「{q}」相符的對話。',
  homeChatGroupToday: '今天',
  homeChatGroupYesterday: '昨天',
  homeChatGroupWeek: '過去 7 天',
  homeChatGroupOlder: '更早',
  homeChatRename: '重新命名',
  homeChatRenameLabel: '對話名稱',
  homeChatDelete: '刪除',
  homeChatDeleted: '已刪除對話',
  homeChatUndo: '復原',
  homeChatClearAll: '清除所有記錄',
  homeChatClearConfirm: '再按一次以全部清除',
  homeChatCleared: '已清除記錄',
  homeChatToggleHistory: '顯示或隱藏聊天記錄',
  homeChatCopy: '複製',
  homeChatCopied: '已複製',
  homeChatRetry: '重試',
  homeChatJumpLatest: '跳到最新',
  homeChatShowEarlier: '顯示更早的 {n} 則訊息',
  homeChatResize: '調整聊天視窗大小',
  homeChatSuggest1: '找出我上週開啟的預算表',
  homeChatSuggest2: '哪些文件提到第三季發表？',
  homeChatSuggest3: '摘要我昨天看的那份合約',
  homeChatSourceStale: '已變更',
  homeChatSourceMissing: '已遺失',
  homeChatSourceStaleHint: '此檔案在讀取後發生變更，請開啟確認。',
  homeChatSourceSkeleton: '僅保留架構',
  homeChatSourceSkeletonHint: '僅保留文件架構，開啟即可閱讀完整內容。',
  homeChatSourceMissingHint: '此檔案已不在原本儲存的位置。',
  homeChatLoadFailed: '無法開啟此對話。',
  homeChatInterrupted: '此回覆已中斷。',
  homeChatWorking: '正在回覆…',
  homeChatDone: '已回覆',
  homeChatErrorChip: '發生錯誤，點擊查看',
  homeChatStopChip: '停止',
  homeChatElapsed: '{n} 秒',
} satisfies Dict

const dicts: LangDicts<Dict> = {
  zh,
  en,
  vi,
  ja,
  ko,
  'zh-TW': zhTW,
  fr: en,
  de: en,
  es: en,
  th: en,
  id: en,
  ru: en,
  ar: en,
  pt: en,
  it: en,
  pl: en,
  cs: en,
  nl: en,
  ms: en,
  he: en,
  hi: en,
}

export type ChatStringKey = keyof typeof zh

const translate = createI18n(dicts)

/** Looks up a Home assistant fork string (history, messages, empty state). */
export function chatString(lang: Lang, key: ChatStringKey, params?: Params): string {
  return translate(lang, key, params)
}

export function isChatStringKey(key: string): key is ChatStringKey {
  return key in en
}
