/// Local background removal for generated pictures, run in a main process. Electron-free: the
/// caller supplies the decoder (see image-cutout-electron.ts), the PNG writer is built in.
///
/// Antigravity's image tool cannot produce alpha: it paints a plain background (the prompt asks for
/// white) into a JPEG. When a caller needs real transparency, the generated bytes go through the
/// same edge flood fill the editors' "remove background" dialogs use (image-cutout-core.ts) and come
/// back as a PNG with alpha. Nothing leaves the machine and nothing is guessed: when the picture
/// cannot be decoded, has no clean border to remove, or the fill would swallow the subject, the
/// outcome says so and the caller keeps the opaque image.

import { deflateSync } from 'node:zlib'
import { removeBackground, sampleBackgroundColors, type PixelImage } from './image-cutout-core'

/** 0..100 colour tolerance: enough to absorb JPEG noise around a flat white backdrop, small enough to keep pale subjects */
export const GENERATED_CUTOUT_TOLERANCE = 14
/** decoded pictures above this many pixels are not processed (flood fill memory is per pixel) */
export const CUTOUT_MAX_PIXELS = 16_000_000
/** less removed than this: the border was not a flat backdrop, so there is nothing honest to cut */
export const CUTOUT_MIN_REMOVED = 0.02
/** more removed than this: the fill swallowed the subject */
export const CUTOUT_MAX_REMOVED = 0.97

export type CutoutFailure =
  'no-decoder' | 'decode-failed' | 'too-large' | 'no-background' | 'subject-lost'

export type CutoutOutcome =
  | { ok: true; png: Uint8Array; removedFraction: number; width: number; height: number }
  | { ok: false; reason: CutoutFailure }

export interface CutoutOptions {
  /** 0..100, default GENERATED_CUTOUT_TOLERANCE */
  tolerance?: number
  /**
   * image bytes -> RGBA pixels; null when the bytes cannot be decoded. An Electron main process
   * passes `decodeWithElectron` from ./image-cutout-electron (kept out of this file so the
   * electron-free CLI bundle can import it); without a decoder nothing is processed.
   */
  decode?: (bytes: Uint8Array) => Promise<PixelImage | null>
  maxPixels?: number
}

// ---------------------------------------------------------------------------
// PNG writer (8-bit RGBA, no interlace)
// ---------------------------------------------------------------------------

const CRC_TABLE = (() => {
  const table = new Uint32Array(256)
  for (let n = 0; n < 256; n++) {
    let c = n
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
    table[n] = c >>> 0
  }
  return table
})()

function crc32(chunk: Uint8Array): number {
  let crc = 0xffffffff
  for (let i = 0; i < chunk.length; i++) crc = CRC_TABLE[(crc ^ chunk[i]!) & 0xff]! ^ (crc >>> 8)
  return (crc ^ 0xffffffff) >>> 0
}

function pngChunk(type: string, body: Uint8Array): Buffer {
  const out = Buffer.alloc(12 + body.length)
  out.writeUInt32BE(body.length, 0)
  out.write(type, 4, 'latin1')
  out.set(body, 8)
  out.writeUInt32BE(crc32(out.subarray(4, 8 + body.length)), 8 + body.length)
  return out
}

/** Encode RGBA pixels as a PNG. */
export function encodePng(image: PixelImage): Uint8Array {
  const { width, height, data } = image
  if (width <= 0 || height <= 0 || data.length < width * height * 4) {
    throw new Error('Cannot encode an empty or truncated image')
  }
  const stride = width * 4
  const raw = Buffer.alloc((stride + 1) * height)
  for (let y = 0; y < height; y++) {
    // filter type 0 (none) in front of every scanline
    raw.set(data.subarray(y * stride, (y + 1) * stride), y * (stride + 1) + 1)
  }
  const header = Buffer.alloc(13)
  header.writeUInt32BE(width, 0)
  header.writeUInt32BE(height, 4)
  header[8] = 8 // bit depth
  header[9] = 6 // colour type: RGBA
  return new Uint8Array(
    Buffer.concat([
      Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
      pngChunk('IHDR', header),
      pngChunk('IDAT', deflateSync(raw, { level: 6 })),
      pngChunk('IEND', new Uint8Array(0)),
    ]),
  )
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

/**
 * Cut the flat backdrop off a generated picture. Returns a PNG with real alpha, or the reason it
 * could not be done honestly (the caller then keeps the opaque picture and says so).
 */
export async function cutoutGeneratedBackground(
  bytes: Uint8Array,
  options: CutoutOptions = {},
): Promise<CutoutOutcome> {
  const decode = options.decode
  if (!decode) return { ok: false, reason: 'no-decoder' }
  let image: PixelImage | null
  try {
    image = await decode(bytes)
  } catch {
    image = null
  }
  if (!image) return { ok: false, reason: 'decode-failed' }
  const total = image.width * image.height
  if (total <= 0 || total > (options.maxPixels ?? CUTOUT_MAX_PIXELS)) {
    return { ok: false, reason: total <= 0 ? 'decode-failed' : 'too-large' }
  }
  const tolerance = options.tolerance ?? GENERATED_CUTOUT_TOLERANCE
  const backdrop = sampleBackgroundColors(image)
  if (backdrop.length === 0) return { ok: false, reason: 'no-background' }
  const { data, removedCount } = removeBackground(image, tolerance, backdrop)
  const removedFraction = removedCount / total
  if (removedFraction < CUTOUT_MIN_REMOVED) return { ok: false, reason: 'no-background' }
  if (removedFraction > CUTOUT_MAX_REMOVED) return { ok: false, reason: 'subject-lost' }
  // transparent pixels carry no colour, so fringe values cannot bleed in when a viewer premultiplies
  for (let i = 0; i < data.length; i += 4) {
    if (data[i + 3] === 0) {
      data[i] = 0
      data[i + 1] = 0
      data[i + 2] = 0
    }
  }
  const png = encodePng({ data, width: image.width, height: image.height })
  return { ok: true, png, removedFraction, width: image.width, height: image.height }
}
